Update event.py
Terrance/SkPy pull request #183
Opened 2021-10-29 12:27 UTC by kingprapop

add attr. of SkypeEndpointEvent(SkypeEvent):
- version
- typ

2021-11-23 07:04 UTC, kingprapop reviewed
thank for review code
sorry for late reply

2021-12-21 04:37 UTC, kingprapop reviewed
thank

2021-12-21 04:39 UTC, kingprapop commented
sorry i don't understand process review

2021-12-21 17:13 UTC, Terrance commented
You need to fix the indenting of your change, and push a follow-up commit as described below the comments.

2022-01-06 13:58 UTC, Terrance requested changes
This still needs some cleanup, but in the interests of getting this wrapped up, I'll see to these.

2022-01-06 13:58 UTC, Terrance commented on skpy/event.py
> +        typ (int):
I'd rather this was called `type` in full -- attributes in SkPy objects prefer readability over mapping to protocol fields.

2022-01-06 13:58 UTC, Terrance commented on skpy/event.py
> +                       "version": res.get("publicInfo", {})
We're now reading `publicInfo` three times, so we ought to pull that out into its own variable.

2022-01-06 13:58 UTC, Terrance commented on skpy/event.py
> +                                 .get("typ",{})})
You're defaulting both `version` and `typ` to an empty dict when not present -- these should be `None` (by omitting the default argument).

2022-01-06 14:10 UTC, merged